# generated by datamodel-codegen:
#   filename:  temp_bgeometrics.json

from __future__ import annotations

from pydantic import BaseModel, RootModel


class BGeometricsTechnicalIndicatorsResponseItem(BaseModel):
    d: str
    unixTs: str
    rsi: float
    macd: float
    macdsignal: float
    macdhist: float
    sma7: float
    sma50: float
    sma200: float
    ema7: float
    ema50: float
    ema200: float


class BGeometricsTechnicalIndicatorsResponse(RootModel[list[BGeometricsTechnicalIndicatorsResponseItem]]):
    root: list[BGeometricsTechnicalIndicatorsResponseItem]
