# generated by datamodel-codegen:
#   filename:  temp_CoinbaseCandleResponse.json

from __future__ import annotations

from pydantic import RootModel


class CoinbaseCandleResponse(RootModel[list[list[float]]]):
    root: list[list[float]]
