# generated by datamodel-codegen:
#   filename:  temp_frankfurter_schema.json

from __future__ import annotations

from pydantic import BaseModel


class Rates(BaseModel):
    EUR: float


class FrankfurterResponse(BaseModel):
    amount: float
    base: str
    start_date: str
    end_date: str
    rates: dict[str, Rates]
