# generated by datamodel-codegen:
#   filename:  temp_FrankfurterResponse.json

from __future__ import annotations

from pydantic import BaseModel


class Rates(BaseModel):
    AUD: float
    BGN: float
    BRL: float
    CAD: float
    CHF: float
    CNY: float
    CZK: float
    DKK: float
    GBP: float
    HKD: float
    HUF: float
    IDR: float
    ILS: float
    INR: float
    ISK: float
    JPY: float
    KRW: float
    MXN: float
    MYR: float
    NOK: float
    NZD: float
    PHP: float
    PLN: float
    RON: float
    SEK: float
    SGD: float
    THB: float
    TRY: float
    USD: float
    ZAR: float


class FrankfurterResponse(BaseModel):
    amount: float
    base: str
    start_date: str
    end_date: str
    rates: dict[str, Rates]
