# generated by datamodel-codegen:
#   filename:  temp_FrankfurterResponse.json

from __future__ import annotations

from pydantic import BaseModel, Field


class CurrencyRates(BaseModel):
    EUR: float


Rates = dict[str, CurrencyRates]


class FrankfurterResponse(BaseModel):
    amount: float
    base: str
    start_date: str
    end_date: str
    rates: Rates
